// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmRr6hAYMDqVtL-W2r1X2nPSsshwRd9a4',
    appId: '1:309153737998:web:b04b9a27f44b75c606bb5f',
    messagingSenderId: '309153737998',
    projectId: 'swaadsansaar-ce6d5',
    authDomain: 'swaadsansaar-ce6d5.firebaseapp.com',
    storageBucket: 'swaadsansaar-ce6d5.appspot.com',
    measurementId: 'G-PG60PBM105',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSBtf2gNyZ69K4ExIfnN64ZXcbWZBBw8U',
    appId: '1:309153737998:android:e8cc78d68fbcaf4f06bb5f',
    messagingSenderId: '309153737998',
    projectId: 'swaadsansaar-ce6d5',
    storageBucket: 'swaadsansaar-ce6d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp04PndEdWFpVrMTxZdKags04rsyTOwx8',
    appId: '1:309153737998:ios:a094b78a227935d806bb5f',
    messagingSenderId: '309153737998',
    projectId: 'swaadsansaar-ce6d5',
    storageBucket: 'swaadsansaar-ce6d5.appspot.com',
    iosBundleId: 'com.example.swaadSansaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp04PndEdWFpVrMTxZdKags04rsyTOwx8',
    appId: '1:309153737998:ios:a094b78a227935d806bb5f',
    messagingSenderId: '309153737998',
    projectId: 'swaadsansaar-ce6d5',
    storageBucket: 'swaadsansaar-ce6d5.appspot.com',
    iosBundleId: 'com.example.swaadSansaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmRr6hAYMDqVtL-W2r1X2nPSsshwRd9a4',
    appId: '1:309153737998:web:71c19d33a1e912b906bb5f',
    messagingSenderId: '309153737998',
    projectId: 'swaadsansaar-ce6d5',
    authDomain: 'swaadsansaar-ce6d5.firebaseapp.com',
    storageBucket: 'swaadsansaar-ce6d5.appspot.com',
    measurementId: 'G-R0R4BBKSBN',
  );
}
